import { useEffect, useState, useMemo } from "react";
import {
  Card,
  CardHeader,
  CardContent,
  Typography,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  Chip,
  Paper,
  CircularProgress,
  Box,
  Tooltip,
  TextField,
  InputAdornment,
  Select,
  MenuItem,
  FormControl,
  InputLabel,
  TablePagination,
  Grid,
  Badge,
} from "@mui/material";
import {
  QuestionAnswer as QuestionAnswerIcon,
  Schedule as ScheduleIcon,
  Search as SearchIcon,
  FilterList as FilterListIcon,
} from "@mui/icons-material";
import { styled, alpha } from "@mui/material/styles";
import conversationApi from "@/api/Conversation/conversationApi";

// Styled components
const StyledCard = styled(Card)(() => ({
  borderRadius: 16,
  boxShadow: '0 8px 32px rgba(0,0,0,0.08)',
  border: `1px solid ${alpha('#1976d2', 0.1)}`,
}));

const StyledTableHead = styled(TableHead)(({ theme }) => ({
  '& .MuiTableCell-head': {
    backgroundColor: theme.palette.grey[50],
    fontWeight: 700,
    fontSize: '0.875rem',
    color: theme.palette.text.primary,
    borderBottom: `2px solid #1976d2`,
    position: 'sticky',
    top: 0,
    zIndex: 10,
  },
}));

const StyledTableRow = styled(TableRow)(({ theme }) => ({
  '&:hover': {
    backgroundColor: alpha('#1976d2', 0.04),
  },
  '& .MuiTableCell-root': {
    borderBottom: `1px solid ${theme.palette.divider}`,
    padding: '12px 16px',
    fontSize: '0.875rem',
  },
}));

const CompactTextField = styled(TextField)(() => ({
  '& .MuiOutlinedInput-root': {
    height: '40px',
    fontSize: '0.875rem',
  },
}));

const StatsCard = styled(Paper)(({ theme }) => ({
  padding: theme.spacing(2),
  borderRadius: 12,
  background: `linear-gradient(135deg, ${alpha(theme.palette.primary.main, 0.05)}, ${alpha(theme.palette.primary.main, 0.02)})`,
  border: `1px solid ${alpha('#1976d2', 0.1)}`,
  textAlign: 'center',
}));

// Status chip component
const StatusChip = ({ status }) => {
  const config = {
    answered: { label: "Đã trả lời", color: "success" },
    not_found: { label: "Không tìm thấy", color: "error" },
    auto_generated: { label: "Tự sinh", color: "warning" },
    out_of_topic: { label: "Lạc đề", color: "default" },
  };

  const item = config[status] || { label: status, color: "default" };
  return (
    <Chip 
      label={item.label} 
      color={item.color} 
      size="small" 
      variant="outlined"
      sx={{ minWidth: 100 }}
    />
  );
};

export default function ConversationLogTable() {
  const [logs, setLogs] = useState([]);
  const [loading, setLoading] = useState(true);
  const [page, setPage] = useState(0);
  const [rowsPerPage, setRowsPerPage] = useState(25);
  const [searchTerm, setSearchTerm] = useState('');
  const [statusFilter, setStatusFilter] = useState('');

  useEffect(() => {
    const fetchLogs = async () => {
      try {
        const res = await conversationApi.getAll();
        const data = res.data || [];
 
        setLogs(
            data.map((item) => ({
                id: item.id,
                question: item.question,
                context: item.context,
                answer: item.answer,
                status: item.response_type,
                created_at: new Date(item.created_at).toLocaleString("vi-VN", {
                day: '2-digit',
                month: '2-digit', 
                year: 'numeric',
                hour: '2-digit',
                minute: '2-digit'
                }),
            }))
        );
      } catch (err) {
        console.error("Lỗi khi lấy logs:", err);
      } finally {
        setLoading(false);
      }
    };

    fetchLogs();
  }, []);

  // Filtered and paginated data
  const filteredLogs = useMemo(() => {
    return logs.filter((log) => {
      const matchesSearch = searchTerm === '' || 
        log.question.toLowerCase().includes(searchTerm.toLowerCase()) ||
        log.answer.toLowerCase().includes(searchTerm.toLowerCase());
      
      const matchesStatus = statusFilter === '' || log.status === statusFilter;
      
      return matchesSearch && matchesStatus;
    });
  }, [logs, searchTerm, statusFilter]);

  const paginatedLogs = useMemo(() => {
    const startIndex = page * rowsPerPage;
    return filteredLogs.slice(startIndex, startIndex + rowsPerPage);
  }, [filteredLogs, page, rowsPerPage]);

  // Statistics
  const stats = useMemo(() => {
    const total = logs.length;
    const answered = logs.filter(log => log.status === 'answered').length;
    const notFound = logs.filter(log => log.status === 'not_found').length;
    const autoGenerated = logs.filter(log => log.status === 'auto_generated').length;
    
    return { total, answered, notFound, autoGenerated };
  }, [logs]);

  const truncate = (text, maxLength = 60) =>
    text?.length > maxLength ? text.substring(0, maxLength) + "..." : text;

  const handleChangePage = (event, newPage) => {
    setPage(newPage);
  };

  const handleChangeRowsPerPage = (event) => {
    setRowsPerPage(parseInt(event.target.value, 10));
    setPage(0);
  };

  const handleSearchChange = (event) => {
    setSearchTerm(event.target.value);
    setPage(0);
  };

  const handleStatusFilterChange = (event) => {
    setStatusFilter(event.target.value);
    setPage(0);
  };

  return (
    <StyledCard>
      <CardHeader
        title={
          <Box display="flex" alignItems="center" justifyContent="space-between">
            <Box display="flex" alignItems="center" gap={2}>
              <QuestionAnswerIcon color="primary" sx={{ fontSize: 28 }} />
              <Box>
                <Typography variant="h5" fontWeight={700} color="primary">
                  Nhật ký hội thoại Chatbot
                </Typography>
                <Typography variant="body2" color="text.secondary">
                  Quản lý và theo dõi các cuộc hội thoại
                </Typography>
              </Box>
            </Box>
            <Badge badgeContent={filteredLogs.length} color="primary" max={9999}>
              <Box sx={{ 
                backgroundColor: alpha('#1976d2', 0.1), 
                padding: 1, 
                borderRadius: 2,
                minWidth: 60,
                textAlign: 'center'
              }}>
                <Typography variant="h6" fontWeight={600} color="primary">
                  {logs.length}
                </Typography>
                <Typography variant="caption" color="text.secondary">
                  Tổng
                </Typography>
              </Box>
            </Badge>
          </Box>
        }
        sx={{ pb: 1 }}
      />
      
      <CardContent sx={{ pt: 0 }}>
        {/* Statistics Cards */}
        <Grid container spacing={2} sx={{ mb: 3 }}>
          <Grid item xs={6} sm={3}>
            <StatsCard>
              <Typography variant="h4" fontWeight={700} color="success.main">
                {stats.answered}
              </Typography>
              <Typography variant="caption" color="text.secondary">
                Đã trả lời
              </Typography>
            </StatsCard>
          </Grid>
          <Grid item xs={6} sm={3}>
            <StatsCard>
              <Typography variant="h4" fontWeight={700} color="error.main">
                {stats.notFound}
              </Typography>
              <Typography variant="caption" color="text.secondary">
                Không tìm thấy
              </Typography>
            </StatsCard>
          </Grid>
          <Grid item xs={6} sm={3}>
            <StatsCard>
              <Typography variant="h4" fontWeight={700} color="warning.main">
                {stats.autoGenerated}
              </Typography>
              <Typography variant="caption" color="text.secondary">
                Tự sinh
              </Typography>
            </StatsCard>
          </Grid>
          <Grid item xs={6} sm={3}>
            <StatsCard>
              <Typography variant="h4" fontWeight={700} color="primary.main">
                {((stats.answered / stats.total) * 100 || 0).toFixed(1)}%
              </Typography>
              <Typography variant="caption" color="text.secondary">
                Tỷ lệ trả lời
              </Typography>
            </StatsCard>
          </Grid>
        </Grid>

        {/* Filters */}
        <Box display="flex" gap={2} mb={3} flexWrap="wrap">
          <CompactTextField
            placeholder="Tìm kiếm câu hỏi, câu trả lời..."
            value={searchTerm}
            onChange={handleSearchChange}
            InputProps={{
              startAdornment: (
                <InputAdornment position="start">
                  <SearchIcon color="action" />
                </InputAdornment>
              ),
            }}
            sx={{ flexGrow: 1, minWidth: 300 }}
          />
          
          <FormControl sx={{ minWidth: 180 }}>
            <InputLabel size="small">Trạng thái</InputLabel>
            <Select
              value={statusFilter}
              onChange={handleStatusFilterChange}
              label="Trạng thái"
              size="small"
              startAdornment={<FilterListIcon sx={{ mr: 1, color: 'action.active' }} />}
            >
              <MenuItem value="">Tất cả</MenuItem>
              <MenuItem value="answered">Đã trả lời</MenuItem>
              <MenuItem value="not_found">Không tìm thấy</MenuItem>
              <MenuItem value="auto_generated">Tự sinh</MenuItem>
              <MenuItem value="out_of_topic">Lạc đề</MenuItem>
            </Select>
          </FormControl>
        </Box>

        {loading ? (
          <Box display="flex" flexDirection="column" alignItems="center" py={8}>
            <CircularProgress size={48} />
            <Typography variant="body1" sx={{ mt: 2, color: "text.secondary" }}>
              Đang tải dữ liệu...
            </Typography>
          </Box>
        ) : (
          <>
            <TableContainer 
              component={Paper} 
              elevation={0} 
              sx={{ 
                borderRadius: 2,
                border: '1px solid',
                borderColor: 'divider',
                maxHeight: 600,
                overflow: 'auto'
              }}
            >
              <Table stickyHeader size="small">
                <StyledTableHead>
                  <TableRow>
                    <TableCell sx={{ width: 60 }} align="center">ID</TableCell>
                    <TableCell sx={{ minWidth: 200 }} align="center">Câu hỏi người dùng</TableCell>
                    <TableCell sx={{ minWidth: 150 }} align="center">Ngữ cảnh</TableCell>
                    <TableCell sx={{ minWidth: 250 }} align="center">Câu trả lời</TableCell>
                    <TableCell align="center" sx={{ width: 130 }}>Trạng thái</TableCell>
                    <TableCell align="center" sx={{ width: 140 }}>Thời gian</TableCell>
                  </TableRow>
                </StyledTableHead>
                <TableBody>
                  {paginatedLogs.map((row) => (
                    <StyledTableRow key={row.id}>
                      <TableCell>
                        <Box
                          sx={{
                            display: 'inline-flex',
                            alignItems: 'center',
                            justifyContent: 'center',
                            width: 32,
                            height: 32,
                            borderRadius: '50%',
                            backgroundColor: alpha('#1976d2', 0.1), 
                            color: 'primary.main',
                            fontSize: '0.875rem',
                            fontWeight: 600,
                          }}
                        >
                          {row.id}
                        </Box>
                      </TableCell>
                      
                      <TableCell>
                        <Tooltip title={row.question} arrow placement="top">
                          <Typography 
                            variant="body2" 
                            sx={{ 
                              fontWeight: 500,
                              cursor: 'pointer',
                              '&:hover': { color: 'primary.main' }
                            }}
                          >
                            {truncate(row.question, 50)}
                          </Typography>
                        </Tooltip>
                      </TableCell>
                      
                      <TableCell>
                        <Tooltip title={row.context || "Không có ngữ cảnh"} arrow placement="top">
                          <Typography 
                            variant="body2" 
                            sx={{ 
                              fontStyle: 'italic', 
                              color: 'text.secondary',
                              cursor: row.context ? 'pointer' : 'default'
                            }}
                          >
                            {truncate(row.context || "-", 35)}
                          </Typography>
                        </Tooltip>
                      </TableCell>
                      
                      <TableCell>
                        <Tooltip title={row.answer} arrow placement="top">
                          <Typography 
                            variant="body2"
                            sx={{ cursor: 'pointer' }}
                          >
                            {truncate(row.answer, 60)}
                          </Typography>
                        </Tooltip>
                      </TableCell>
                      
                      <TableCell align="center">
                        <StatusChip status={row.status} />
                      </TableCell>
                      
                      <TableCell align="center">
                        <Box display="flex" alignItems="center" justifyContent="center" gap={0.5}>
                          <ScheduleIcon sx={{ fontSize: 14, color: "text.disabled" }} />
                          <Typography variant="caption" color="text.secondary">
                            {row.created_at}
                          </Typography>
                        </Box>
                      </TableCell>
                    </StyledTableRow>
                  ))}
                  
                  {paginatedLogs.length === 0 && (
                    <TableRow>
                      <TableCell colSpan={6} align="center" sx={{ py: 4 }}>
                        <Typography variant="body1" color="text.secondary">
                          Không tìm thấy dữ liệu phù hợp
                        </Typography>
                      </TableCell>
                    </TableRow>
                  )}
                </TableBody>
              </Table>
            </TableContainer>

            {/* Pagination */}
            <TablePagination
              component="div"
              count={filteredLogs.length}
              page={page}
              onPageChange={handleChangePage}
              rowsPerPage={rowsPerPage}
              onRowsPerPageChange={handleChangeRowsPerPage}
              rowsPerPageOptions={[10, 25, 50, 100]}
              labelRowsPerPage="Hiển thị:"
              labelDisplayedRows={({ from, to, count }) => 
                `${from}-${to} trong tổng số ${count !== -1 ? count : `hơn ${to}`}`
              }
              sx={{
                borderTop: '1px solid',
                borderColor: 'divider',
                '& .MuiTablePagination-toolbar': {
                  paddingLeft: 2,
                  paddingRight: 2,
                },
                '& .MuiTablePagination-selectLabel, & .MuiTablePagination-displayedRows': {
                  fontSize: '0.875rem',
                },
              }}
            />
          </>
        )}
      </CardContent>
    </StyledCard>
  );
}