"""LLM Gateway and provider abstraction contracts.

Decouples domain graph and LangGraph orchestration from specific LLM providers
(Gemini, OpenAI, vLLM/Ollama) and LiteLLM adapters.
"""

from typing import Any, Dict, List, Literal, Optional, Protocol, runtime_checkable
from pydantic import BaseModel, Field, model_validator


class ChatMessage(BaseModel):
    """Vendor-neutral chat turn representation."""
    role: Literal["system", "user", "assistant", "tool"] = Field(
        ...,
        description="Role of message sender",
    )
    content: str = Field(..., description="Message text content")
    name: Optional[str] = Field(
        default=None,
        description="Name of tool or function if role == tool",
    )


class TokenUsage(BaseModel):
    """Token accounting and cost metrics."""
    prompt_tokens: int = Field(default=0, ge=0)
    completion_tokens: int = Field(default=0, ge=0)
    total_tokens: int = Field(default=0, ge=0)
    estimated_cost_usd: Optional[float] = Field(default=None, ge=0.0)


class GenerationRequest(BaseModel):
    """Vendor-neutral model generation specification."""
    request_id: str = Field(..., description="Trace UUID for call correlation")
    messages: List[ChatMessage] = Field(
        default_factory=list,
        description="Chronological chat history including system instruction",
    )
    prompt: Optional[str] = Field(
        default=None,
        description="Single prompt shorthand (automatically converted to user message)",
    )
    system_prompt: Optional[str] = Field(
        default=None,
        description="System instruction shorthand (automatically prepended)",
    )
    temperature: float = Field(
        default=0.2,
        ge=0.0,
        le=1.0,
        description="Low temperature for factual grounded answers",
    )
    max_tokens: Optional[int] = Field(
        default=1024,
        ge=1,
        le=8192,
        description="Maximum tokens to generate",
    )
    top_p: Optional[float] = Field(default=0.95, ge=0.0, le=1.0)
    response_format: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Structured JSON format spec (e.g. {'type': 'json_object'})",
    )
    json_schema: Optional[Dict[str, Any]] = Field(
        default=None,
        description="JSON schema definition for structured validation",
    )
    stop_sequences: Optional[List[str]] = Field(default=None)
    timeout_seconds: float = Field(default=20.0, ge=1.0, le=60.0)
    external_calls_already_made: int = Field(
        default=0,
        ge=0,
        le=10,
        description="Count of external AI calls already made for this request (enforced by gateway)",
    )

    @model_validator(mode="before")
    @classmethod
    def assemble_messages_from_prompt(cls, data: Any) -> Any:
        if isinstance(data, dict):
            messages: List[Dict[str, Any]] = list(data.get("messages") or [])
            sys_prompt = data.get("system_prompt")
            prompt = data.get("prompt")

            if sys_prompt and not any(m.get("role") == "system" for m in messages):
                messages.insert(0, {"role": "system", "content": sys_prompt})

            if prompt and not any(m.get("role") == "user" for m in messages):
                messages.append({"role": "user", "content": prompt})

            data["messages"] = messages
        return data

    @model_validator(mode="after")
    def validate_budget_ceiling(self) -> "GenerationRequest":
        if self.external_calls_already_made > 10:
            raise ValueError("Call budget exceeded: external_calls_already_made cannot exceed 10")
        if not self.messages:
            raise ValueError("messages list cannot be empty for GenerationRequest")
        return self


class GenerationResult(BaseModel):
    """Standardized LLM generation output with usage and metadata."""
    content: str = Field(..., description="Raw text generated by the model")
    parsed_json: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Locally validated or repaired JSON object if response_format was JSON",
    )
    structured_output: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Alias for parsed_json",
    )
    usage: TokenUsage = Field(default_factory=TokenUsage)
    tokens: Optional[TokenUsage] = Field(
        default=None,
        description="Alias for usage",
    )
    model_name: str = Field(..., description="Model identifier used (e.g. 'gemini-3.5-flash')")
    model: Optional[str] = Field(
        default=None,
        description="Alias for model_name",
    )
    provider: str = Field(
        ...,
        description="Active provider identifier ('gemini', 'openai', 'openai_compatible')",
    )
    latency_ms: int = Field(..., ge=0, description="Model generation latency in ms")
    finish_reason: Literal["stop", "length", "tool_calls", "content_filter", "error"] = Field(
        default="stop",
        description="Reason generation terminated",
    )

    @model_validator(mode="after")
    def sync_aliases(self) -> "GenerationResult":
        if self.structured_output is None:
            self.structured_output = self.parsed_json
        if self.parsed_json is None:
            self.parsed_json = self.structured_output
        if self.tokens is None:
            self.tokens = self.usage
        if self.model is None:
            self.model = self.model_name
        return self


class ProviderCapability(BaseModel):
    """Declarative configuration of model provider capabilities."""
    provider_name: Literal["gemini", "openai", "openai_compatible"]
    supports_native_json: bool = Field(
        default=True,
        description="True if model guarantees RFC 8259 JSON output via API",
    )
    supports_json_schema: bool = Field(
        default=True,
        description="True if model supports strict JSON schema enforcement",
    )
    supports_tool_calling: bool = Field(
        default=True,
        description="True if model supports native function/tool call payloads",
    )
    supports_system_prompt: bool = Field(default=True)
    max_context_tokens: int = Field(default=32768)
    max_output_tokens: int = Field(default=4096)
    local_repair_required: bool = Field(
        default=False,
        description="If True, output must pass through local JSON repair before validation",
    )


class ModelConfig(BaseModel):
    """Active LLM provider configuration."""
    provider: Literal["gemini", "openai", "openai_compatible"] = Field(
        default="gemini",
        description="Active provider configured via LLM_PROVIDER",
    )
    model: str = Field(
        default="gemini-3.5-flash",
        description="Model name configured via LLM_MODEL",
    )
    api_key: Optional[str] = Field(default=None, description="API key from environment")
    base_url: Optional[str] = Field(default=None, description="Base URL for local vLLM/Ollama")
    timeout_seconds: float = Field(default=20.0, description="Per-request timeout")
    max_external_calls: int = Field(default=2, description="Hard ceiling on external calls")
    fallback_provider: Optional[str] = Field(default=None, description="Fallback provider")
    fallback_model: Optional[str] = Field(default=None, description="Fallback model")
    capabilities: ProviderCapability = Field(
        default_factory=lambda: ProviderCapability(
            provider_name="gemini",
            supports_native_json=True,
            supports_json_schema=True,
            supports_tool_calling=True,
        )
    )


@runtime_checkable
class LLMPort(Protocol):
    """Abstract Port decoupling LangGraph and domain logic from model providers."""

    async def generate(self, request: GenerationRequest) -> GenerationResult:
        """Executes generation against active provider with timeout and budget tracking.

        Raises:
            CallBudgetExceededError: If request exceeds 2 external calls.
            ProviderTimeoutError: If call exceeds timeout_seconds.
            ProviderUnavailableError: If provider returns 5xx and fallback fails.
        """
        ...

    async def get_active_model_config(self) -> ModelConfig:
        """Returns active model configuration and capability profile."""
        ...
