create table if not exists public.support_cases (
  id bigint generated by default as identity primary key,
  tenant_id text not null,
  account_id bigint not null references public.accounts(id) on delete restrict,
  category varchar(80) not null,
  subject varchar(200) not null,
  details varchar(4000) not null,
  priority varchar(16) not null default 'normal'
    check (priority in ('low', 'normal', 'high', 'urgent')),
  status varchar(16) not null default 'open'
    check (status in ('open', 'assigned', 'resolved', 'closed')),
  conversation_id varchar(128),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists support_cases_tenant_status_created_idx
  on public.support_cases (tenant_id, status, created_at desc);

alter table public.support_cases enable row level security;
revoke all on public.support_cases from anon, authenticated;
grant select, insert, update on public.support_cases to service_role;
grant usage, select on sequence public.support_cases_id_seq to service_role;
