begin;

create table if not exists public.student_profiles (
  account_id bigint primary key references public.accounts(id) on delete cascade,
  tenant_id text not null default 'vnua',
  student_code text not null,
  faculty text,
  program text,
  cohort text,
  updated_at timestamptz not null default now(),
  unique (tenant_id, student_code)
);

create table if not exists public.student_schedule_entries (
  id bigint generated by default as identity primary key,
  account_id bigint not null references public.accounts(id) on delete cascade,
  tenant_id text not null default 'vnua',
  semester text not null,
  week integer check (week between 1 and 53),
  day_of_week integer check (day_of_week between 1 and 7),
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  course_code text not null,
  course_name text not null,
  room text,
  event_type text not null default 'class' check (event_type in ('class', 'exam')),
  source_system text not null,
  source_updated_at timestamptz,
  updated_at timestamptz not null default now(),
  check (ends_at > starts_at)
);

create table if not exists public.student_tuition_entries (
  id bigint generated by default as identity primary key,
  account_id bigint not null references public.accounts(id) on delete cascade,
  tenant_id text not null default 'vnua',
  semester text not null,
  item_code text not null,
  description text not null,
  amount_due numeric(14,2) not null default 0 check (amount_due >= 0),
  amount_paid numeric(14,2) not null default 0 check (amount_paid >= 0),
  due_date date,
  currency char(3) not null default 'VND',
  source_system text not null,
  source_updated_at timestamptz,
  updated_at timestamptz not null default now(),
  unique (tenant_id, account_id, semester, item_code)
);

create index if not exists student_schedule_lookup_idx
  on public.student_schedule_entries (tenant_id, account_id, semester, starts_at);
create index if not exists student_tuition_lookup_idx
  on public.student_tuition_entries (tenant_id, account_id, semester);

alter table public.student_profiles enable row level security;
alter table public.student_schedule_entries enable row level security;
alter table public.student_tuition_entries enable row level security;

-- Browser roles receive no grants. Node's service-role client is the only application reader.
revoke all on public.student_profiles, public.student_schedule_entries,
  public.student_tuition_entries from anon, authenticated;

commit;
