-- ==============================================================================
-- ST-CARE VNUA - ALL-IN-ONE SUPABASE SCHEMA MIGRATION
-- Chạy 1 lần duy nhất trong Supabase SQL Editor để cấu hình toàn bộ DB cho core-ai
-- ==============================================================================

begin;

-- 1. Extensions
create extension if not exists pgcrypto with schema extensions;
create extension if not exists vector;

-- 2. Security Roles cho AI Service
do $$
begin
  if not exists (select 1 from pg_roles where rolname = 'st_ai_agent') then
    create role st_ai_agent nologin;
  end if;
  if not exists (select 1 from pg_roles where rolname = 'st_ai_ingestion_worker') then
    create role st_ai_ingestion_worker nologin;
  end if;
end $$;

grant usage on schema public to st_ai_agent, st_ai_ingestion_worker;

-- 3. Bổ sung cột cho các bảng hiện hữu (documents, document_chunks, questions)
alter table public.documents
  add column if not exists tenant_id text not null default 'vnua',
  add column if not exists created_by bigint,
  add column if not exists content_sha256 text,
  add column if not exists knowledge_version bigint not null default 1,
  add column if not exists ingestion_quality numeric(5,4),
  add column if not exists embedding_model text,
  add column if not exists embedding_dimension integer,
  add column if not exists source_trust numeric(5,4) not null default 0.80,
  add column if not exists valid_from timestamptz,
  add column if not exists valid_to timestamptz;

alter table public.document_chunks
  add column if not exists tenant_id text not null default 'vnua',
  add column if not exists chunk_index integer default 0,
  add column if not exists embedding_model text,
  add column if not exists embedding_dimension integer,
  add column if not exists content_hash text,
  add column if not exists heading_path jsonb not null default '[]'::jsonb,
  add column if not exists parser_used text,
  add column if not exists ocr_confidence numeric(5,4),
  add column if not exists knowledge_version bigint not null default 1;

alter table public.questions
  add column if not exists tenant_id text not null default 'vnua',
  add column if not exists embedding_model text,
  add column if not exists embedding_dimension integer;

-- 4. Tạo các bảng mới cho Core AI & Dữ liệu sinh viên
create table if not exists public.support_cases (
  id bigint generated by default as identity primary key,
  tenant_id text not null default 'vnua',
  account_id bigint not null references public.accounts(id) on delete restrict,
  category varchar(80) not null,
  subject varchar(200) not null,
  details varchar(4000) not null,
  priority varchar(16) not null default 'normal' check (priority in ('low', 'normal', 'high', 'urgent')),
  status varchar(16) not null default 'open' check (status in ('open', 'assigned', 'resolved', 'closed')),
  conversation_id varchar(128),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.ai_knowledge_versions (
  tenant_id text primary key,
  version bigint not null default 1,
  updated_at timestamptz not null default now()
);

create table if not exists public.ai_topic_anchors (
  tenant_id text not null,
  topic text not null,
  embedding vector(1024) not null,
  embedding_model text not null,
  embedding_dimension integer not null check (embedding_dimension = 1024),
  updated_at timestamptz not null default now(),
  primary key (tenant_id, topic, embedding_model, embedding_dimension)
);

create table if not exists public.student_profiles (
  account_id bigint primary key references public.accounts(id) on delete cascade,
  tenant_id text not null default 'vnua',
  student_code text not null,
  faculty text,
  program text,
  cohort text,
  updated_at timestamptz not null default now(),
  unique (tenant_id, student_code)
);

create table if not exists public.student_schedule_entries (
  id bigint generated by default as identity primary key,
  account_id bigint not null references public.accounts(id) on delete cascade,
  tenant_id text not null default 'vnua',
  semester text not null,
  week integer check (week between 1 and 53),
  day_of_week integer check (day_of_week between 1 and 7),
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  course_code text not null,
  course_name text not null,
  room text,
  event_type text not null default 'class' check (event_type in ('class', 'exam')),
  source_system text not null default 'daotao_vnua',
  source_updated_at timestamptz,
  updated_at timestamptz not null default now(),
  check (ends_at > starts_at)
);

create table if not exists public.student_tuition_entries (
  id bigint generated by default as identity primary key,
  account_id bigint not null references public.accounts(id) on delete cascade,
  tenant_id text not null default 'vnua',
  semester text not null,
  item_code text not null,
  description text not null,
  amount_due numeric(14,2) not null default 0 check (amount_due >= 0),
  amount_paid numeric(14,2) not null default 0 check (amount_paid >= 0),
  due_date date,
  currency char(3) not null default 'VND',
  source_system text not null default 'finance_vnua',
  source_updated_at timestamptz,
  updated_at timestamptz not null default now(),
  unique (tenant_id, account_id, semester, item_code)
);

-- 5. Indexes
create index if not exists documents_tenant_ready_idx
  on public.documents (tenant_id, created_at desc)
  where is_active = true and pipeline_stage = 'ready';

create index if not exists questions_tenant_approved_idx
  on public.questions (tenant_id, created_at desc)
  where status = 'approved';

create index if not exists document_chunks_tenant_document_idx
  on public.document_chunks (tenant_id, document_id, chunk_index);

create index if not exists document_chunks_content_hash_idx
  on public.document_chunks (tenant_id, content_hash, embedding_model, embedding_dimension);

create index if not exists document_chunks_fts_simple_idx
  on public.document_chunks using gin (to_tsvector('simple', content));

create index if not exists support_cases_tenant_status_created_idx
  on public.support_cases (tenant_id, status, created_at desc);

create index if not exists student_schedule_lookup_idx
  on public.student_schedule_entries (tenant_id, account_id, semester, starts_at);

create index if not exists student_tuition_lookup_idx
  on public.student_tuition_entries (tenant_id, account_id, semester);

-- 6. Row Level Security & Permissions
alter table public.documents enable row level security;
alter table public.document_chunks enable row level security;
alter table public.questions enable row level security;
alter table public.support_cases enable row level security;
alter table public.ai_knowledge_versions enable row level security;
alter table public.ai_topic_anchors enable row level security;
alter table public.student_profiles enable row level security;
alter table public.student_schedule_entries enable row level security;
alter table public.student_tuition_entries enable row level security;

-- Quyền cho st_ai_agent
grant select on public.documents, public.document_chunks, public.questions to st_ai_agent;
grant select on public.ai_knowledge_versions, public.ai_topic_anchors to st_ai_agent;

drop policy if exists documents_ai_read on public.documents;
create policy documents_ai_read on public.documents
  for select to st_ai_agent using (true);

drop policy if exists document_chunks_ai_read on public.document_chunks;
create policy document_chunks_ai_read on public.document_chunks
  for select to st_ai_agent using (true);

drop policy if exists questions_ai_read on public.questions;
create policy questions_ai_read on public.questions
  for select to st_ai_agent using (status = 'approved');

commit;
